### PR TITLE
Issues fixing

### LINKED ISSUE #16: Add some indication of current page user is on in the nav bar (bold current page title)
See Navbar.js, and check out https://mui.com/material-ui/react-app-bar/

### LINKED ISSUE #18: Increase spacing in exec picture section of landing page
- Spacing under each row of exec pictures/titles should be larger
- Spacing under the entire exec pictures module should be larger (space above the footer)

See https://www.figma.com/file/KGuUw7i2ds3Lnp6Ox3f3M6/PennApps-Static-Site-Redesign for what the exec picture section should be like

### LINKED ISSUE #19: /hackers, /organizers, /ambassadors - Add hover states for the “APPLY” and “EVENT SITE” buttons (specified on the mockup)
https://www.figma.com/file/KGuUw7i2ds3Lnp6Ox3f3M6/PennApps-Static-Site-Redesign?node-id=0%3A1

### LINKED ISSUE #20: Mobile /ambassadors - Header part should be stacked instead of side by side
https://www.figma.com/file/KGuUw7i2ds3Lnp6Ox3f3M6/PennApps-Static-Site-Redesign?node-id=0%3A1

### LINKED ISSUE #21: Mobile /organizers - Fix margin sizes
https://www.figma.com/file/KGuUw7i2ds3Lnp6Ox3f3M6/PennApps-Static-Site-Redesign?node-id=0%3A1

### PR DESCRIPTION
**Pull request by ydu20**
Fixed issues #16, 18, 19, 20, 21

### CODE REVIEW

File: src/components/Navbar.js [hunk 1]
```diff
@@ -16,8 +16,8 @@ import { Link } from 'gatsby'
 const drawerWidth = 240
 const navItems = ['HACKERS', 'ORGANIZERS', 'AMBASSADORS']
 
-function DrawerAppBar(props) {
-  const { window } = props
+function DrawerAppBar({ currPage }) {
+  // const { window } = props
```
Comment (MechaJoe) [inline src/components/Navbar.js]: nit: remove all comments

File: src/components/Navbar.js [hunk 2]
```diff
@@ -48,7 +48,7 @@ function DrawerAppBar(props) {
     </Box>
   )
 
-  const container = window !== undefined ? () => window().document.body : undefined
+  // const container = window !== undefined ? () => window().document.body : undefined
```
Comment (MechaJoe) [inline src/components/Navbar.js]: nit: remove

File: src/components/Navbar.js [hunk 3]
```diff
@@ -106,7 +106,7 @@ function DrawerAppBar(props) {
       <Box component="nav">
         <Drawer
           anchor="right"
-          container={container}
+          // container={container}
```
Comment (MechaJoe) [inline src/components/Navbar.js]: remove

File: src/pages/ambassadors.js [hunk 4]
```diff
@@ -18,7 +18,7 @@ export function Head() {
 
 export default function Ambassadors() {
   // change this if CA Applications are open or closed
-  const applicationsOpen = false
+  const applicationsOpen = true
```
Comment (MechaJoe) [inline src/pages/ambassadors.js]: Applications are closed for CA right now, so this should be false

File: src/pages/ambassadors.js [hunk 5]
```diff
@@ -32,13 +32,20 @@ export default function Ambassadors() {
     return color
   }
 
+  // const ni = [{ name: 'HACKERS', shown: false }, { name: 'ORGANIZERS', shown: false }, { name: 'AMBASSADORS', shown: true }]
```
Comment (MechaJoe) [inline src/pages/ambassadors.js]: nit: remove

File: src/pages/organizers.js [hunk 6]
```diff
@@ -6,7 +6,9 @@ import ApplicationsIntro from '../components/ApplicationsIntro'
 import ApplicationsProcess from '../components/ApplicationsProcess'
 import ApplicationsCommittees from '../components/ApplicationsCommittees'
 import ApplicationsFAQs from '../components/ApplicationsFAQs'
-import Logo from '../images/logo.svg'
+// import Logo from '../images/logo.svg'
```
Comment (MechaJoe) [inline src/pages/organizers.js]: nit: remove

File: src/pages/organizers.js [hunk 7]
```diff
@@ -19,18 +21,22 @@ export function Head() {
...
-  const applicationsOpen = false
+  const applicationsOpen = true
 
   return (
     <>
-      <Navbar />
+      <Navbar currPage="ORGANIZERS" />
       <div className="applications-header-container">
-        <Logo className="organizers-logo" />
+        {/* <Logo className="organizers-logo" /> */}
```
Comment (MechaJoe) [inline src/pages/organizers.js]: nit: remove

File: src/pages/ambassadors.js [hunk 8]
```diff
@@ -32,13 +32,20 @@ export default function Ambassadors() {
...
+      <Navbar currPage="AMBASSADORS" />
       <div className="ambassador-section">
         <div className="header-section">
           <div>
             <div className="horizontal-align">
+              <div className="horizontal-section">
+                <div className="logo-section">
+                  {applicationsOpen ? (<ApplicationsOpenSvg className='open-closed-logo' />) : (<ApplicationsClosedSvg className='open-closed-logo' />)}
+                </div>
+              </div>
```
Comment (MechaJoe) [inline src/pages/ambassadors.js:46]: `horizontal-align` previously had `flex-direction: row` in the CSS. Is there a reason why you put this on top and switched it to `flex-direction: row-reverse`? It is visually the same, but having the elements flipped in the HTML and then setting `flex-direction: row-reverse` is a bit more confusing

File: src/pages/ambassadors.js [hunk 9]
```diff
@@ -144,6 +146,11 @@ export default function Ambassadors() {
               style={{ backgroundColor: expandedSectionColor(showQ1) }}
             >
               <div className="horizontal-align">
+                <div
+                  className="arrow-button"
+                >
+                  {showQ1 ? <FaChevronDown /> : <FaChevronRight />}
+                </div>
```
Comment (MechaJoe) [inline src/pages/ambassadors.js:151]: See my question on `horizontal-align`; it pertains to this too

File: src/styles/organizers.css [hunk 10]
```diff
@@ -65,9 +89,16 @@ h5 {
...
     cursor: pointer;
-}
+} */
+
+/* .organizers-logo {
+    display: flex;
+    flex-direction: column;
+    vertical-align: middle;
+    width: 30vw;
+} */
```
Comment (MechaJoe) [inline src/styles/organizers.css]: nit: remove

File: src/styles/organizers.css [hunk 11]
```diff
@@ -204,7 +232,11 @@ h5 {
         margin-top: 0px;
     }
 
-    .organizers-logo {
+    /* .organizers-logo {
+        width: 270px;
+    } */
```
Comment (MechaJoe) [inline src/styles/organizers.css]: nit: remove

File: src/components/Navbar.js [hunk 12]
```diff
@@ -84,7 +84,7 @@ function DrawerAppBar(props) {
                 component={Link}
                 to={`/${item}`.toLowerCase()}
                 key={item}
-                sx={{ color: '#0F2944', fontFamily: 'Proxima Nova', mr: '13px' }}
+                sx={{ bgcolor: item === currPage ? 'rgba(25, 118, 210, 0.04)' : '', color: '#0F2944', fontFamily: 'Proxima Nova', mr: '13px' }}
```
Comment (MechaJoe) [inline src/components/Navbar.js]: Consider making the `bgcolor` a bit darker so it's even more clear which page the viewer is on (it's a bit subtle right now)

File: src/components/Navbar.js [hunk 13]
```diff
@@ -16,8 +16,8 @@ import { Link } from 'gatsby'
 const drawerWidth = 240
 const navItems = ['HACKERS', 'ORGANIZERS', 'AMBASSADORS']
 
-function DrawerAppBar(props) {
-  const { window } = props
+function DrawerAppBar({ currPage }) {
```
Comment (MechaJoe) [inline src/components/Navbar.js:19]: Nice object destructuring here

**Review by MechaJoe — CHANGES_REQUESTED** [review]
Great work, Alan--verified in development that this looks fantastic. Will deploy, but when you get around to it, take a look at my feedback (feel free to challenge it if you feel strongly too) before we merge it into main.

File: src/pages/ambassadors.js (hunk 8 above)
Comment (ydu20) [reply src/pages/ambassadors.js:46]: I reversed it because it would've been visually different for mobile view. If it was not reversed, the logo would've been below the "applications are open/closed message" in mobile view, instead of at the top of the page.

**Review by MechaJoe — APPROVED** [review]
